### ISSUE TITLE
Encrypted PDFs

### ISSUE THREAD

**Issue by andhapp** [yob/pdf-reader#1]
It does not read Encrypted PDF files.

**Comment by davidhq** [comment]
So is it possible to read password protected files already? It's not in the documentation.... thank you

**Comment by yob** [comment]
The PDF spec supports a variety of encryption formats. `pdf-reader` can't decrypt any of the formats used to enforce DRM, but it can decrypt the basic style. This spec shows how:
 
https://github.com/yob/pdf-reader/blob/master/spec/integration_spec.rb#L236-L244
