### ISSUE TITLE
PDF::Reader::MalformedPDFError

### ISSUE THREAD

**Issue by danieldms** [yob/pdf-reader#101]
I have a pdf that I'm not getting read. Could you help me?
link file https://dl.dropboxusercontent.com/u/79588315/My%20Uploads/file.pdf

**Comment by yob** [comment]
Yep, it seems like the xref table points to a byte offset that is larger than the total filesize.

Acrobat and Evince open it anyway, which I guess means they manually search for the final xref table in the file if the trailer is incorrect. I'd happily accept a patch for `PDF::Reader::XRef` that implements the same logic.
