### ISSUE TITLE
Unknown glyph width for 9 Times-Roman

### ISSUE THREAD

**Issue by imella** [yob/pdf-reader#102]
Hi guys,

I'm getting this weird error when trying to read a particular PDF. 

https://www.dropbox.com/s/w4fas8190uyxovs/test.pdf

Don't know if it's a problem with the gem or the PDF itself.

Hope you guys can help me.

Thanks!

**Comment by sarink** [comment]
Here's my fix

``
require "pdf-reader"
class PDF::Reader
  module WidthCalculator
    class BuiltIn
      alias :original_glyph_width :glyph_width
      def glyph_width(code_point)
        return 1000 if code_point = 160 || code_point < 0
        original_glyph_width(code_point)
      end
    end
  end
end
``

**Comment by cpayne624** [comment]
Cool thx -c

**Comment by ShockwaveNN** [comment]
As far as I undersand `return 1000 if code_point = 160 || code_point < 0` will ALWAYS return 1000,  because `code_point = 160` is assign variable.
I tried `return 1000 if code_point == 160 || code_point < 0`  but this doesn't work for me.
So I assume whole `glyph_width` method can be replaced with
````def glyph_width
return 1000
end```

**Comment by aarmora** [comment]
But is this actually parsing the PDF correctly?  At that size it doesn't parse it correctly for me.  As in it misses whole characters.

**Comment by ShockwaveNN** [comment]
@aarmora I agree, I don't think it parse pdf correctly, but at least it is not crashing.

**Comment by aarmora** [comment]
That's true.  But when I'm missing half of the characters I need, it's not
very useful.  I'm going to try and mess with the glyph_width and see if
it'll make any difference if I go 500 or something.

**Comment by sarink** [comment]
Wow, never even noticed that. Good catch.

Maybe a better solution would be to wrap a try/catch around ``original_glyph_width(code_point)`` and if it errors, then return 1000

**Comment by aarmora** [comment]
I like your style and I am going to do just that.  Using 500 was a bit
better.  I'm not sure what I'm losing by using 500, though.
