### ISSUE TITLE
Invalid Password

### ISSUE THREAD

**Issue by normancapule** [yob/pdf-reader#108]
Hello,

I'm trying to open a PDF generated from Echosign using this gem. The pdf does not require any password to open it. Here is my code snippet:

page_count = PDF::Reader.new(input).page_count
Prawn::Document.generate(output, :skip_page_creation => true) do |pdf|

But, this results to the error message:

PDF::Reader::EncryptedPDFError - Invalid password ():
   () .../bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/standard_security_handler.rb:186:in `build_standard_key'
   () .../bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/standard_security_handler.rb:68:in`initialize'
   () .../bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/object_hash.rb:275:in `new'
   () .../bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/object_hash.rb:275:in`build_security_handler'
   () .../bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/object_hash.rb:48:in `initialize'
   () .../bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader.rb:117:in`new'
   () .../bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader.rb:117:in `initialize'

Can you please help? Thanks!

**Comment by yob** [comment]
Thanks for this report, and apologies for not replying sooner.

I've just merged some fixes for encrypted files to master (see #189), and I think there's a high chance it'll solve this long standing issue.

If not and it's still not working for you, feel free to re-open the issue

**Comment by normancapule** [comment]
Cheers! Though Im not sure if I can replicate this again. Been a long time since Ive used echosign. haha

If ever I use it again, will report back if this didnt fix it.
