### ISSUE TITLE
ExtractImages example using native endian packing with little endian format for TIFF

### ISSUE THREAD

**Issue by palfvin** [yob/pdf-reader#116]
I know it's just an example and there aren't a lot of big-endian machines around these days, but the tiff header generated by the following:

```
  tiff = [ 73, 73, 42, 8, 5 ].pack("ccsIs") \
```

in extract_images.rb Is specifying "little endian" format with the `73, 73` (`"II"`) per page 13 of http://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf, but the `s` and `I` formats  passed to pack indicates "native-endian" format.  To enable the code to produce correct output on a big-endian machines, the instances of `s` and `I` need to be changed to `s<` and `v`, respectively (if I'm reading http://ruby-doc.org/core-2.0.0/Array.html#method-i-pack correctly).

**Comment by yob** [comment]
Thanks for reporting this.

Unfortunately I'm short on time at the moment so probably won't make this change myself. I'm happy to review and merge a patch if you're interested in making one though,
