### ISSUE TITLE
Unable to parse pdf file using pdf-reader gem - Unknown glyph width for 160 Times-Bold (PDF::Reader::MalformedPDFError) error

### ISSUE THREAD

**Issue by raagu** [yob/pdf-reader#117]
Hello All

I am trying to parse a pdf using pdf-reader gem and in my code I am doing a simple call page.text for which I am getting following exception 

G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/width_calculator/built_in.rb:95:in `glyph_width': Unknown glyph width for 160 Times-Bold (PDF::Reader::MalformedPDFError)
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/font.rb:81:in `glyph_width'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page_text_receiver.rb:107:in `block in internal_show_text'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page_text_receiver.rb:100:in `each'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page_text_receiver.rb:100:in `each_with_index'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page_text_receiver.rb:100:in `internal_show_text'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page_text_receiver.rb:57:in `show_text'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page.rb:160:in `block in callback'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page.rb:159:in `each'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page.rb:159:in `callback'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page.rb:146:in `content_stream'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page.rb:111:in `walk'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader/page.rb:81:in `text'
        from parseByRawText.rb:111:in `block (2 levels) in start'
        from parseByRawText.rb:109:in `each'
        from parseByRawText.rb:109:in `block in start'
        from G:/RubyOnRails/applications/pdf-parser/vendor/ruby/2.0.0/bundler/gems/pdf-reader-1f034aa035ee/lib/pdf/reader.rb:164:in `open'
        from parseByRawText.rb:107:in `start'
        from parseByRawText.rb:125:in `<main>'
		
I have looked at similar issue at https://github.com/yob/pdf-reader/issues/102 and saw that it is currently fixed in master. Then I had tried executing my ruby script using master branch of pdf-reader from git. Still its I am getting same exception as above. 

I have attached my sample ruby code and pdf document in the google group for pdf-reader at https://groups.google.com/forum/#!topic/pdf-reader/69_ATsUmxIg.
		
Can you please tell me what is going wrong here and how to resolve this issue ?

**Comment by yob** [comment]
Thanks for reporting this, and apologies for the disappointingly slow response. I believe the issue has been fixed in todays `1.4.0` release
