### ISSUE TITLE
Parsing of string and \n

### ISSUE THREAD

**Issue by p13rr3-yv3s** [yob/pdf-reader#129]
Hi,
If a string has a line feed within it's content, it will be parsed as such and not ignored.

For example the string in the array below :
[100.1 (\110\145\n\154\154\157)]TJ

Will be parsed to "He\nllo". 
Now I am not sure though what should be the right behaviour in case of valid Carriage Return / Line feed in a text, but I thought it would be escaped ("\\n")
Existing code although expect the \n to be kept in string ( and not in Hex)
    parse_string("(x\nx)").parse_token.should eql("x\nx")
    parse_string("(x\rx)").parse_token.should eql("x\nx")
    parse_string("(x\r\nx)").parse_token.should eql("x\nx")

**Comment by yob** [comment]
I'm not 100% sure on what the spec requires us to do here. In the absence of additional info I'm going to close this issue, but feel free to open it if you want to continue the discussion.
