### ISSUE TITLE
Parsing of Landscape pages

### ISSUE THREAD

**Issue by Shwetakale** [yob/pdf-reader#134]
When i am trying to convert landscape pages in plain text its reading contents in random order and i am also losing some data in plain text.

Attributes for landscape page is:

```
{:Parent=>#<PDF::Reader::Reference:0x00000007edc360 @id=11481, @gen=0>, :Type=>:Page, :Resources=>{:Font=>{:Fcpdf0=>#<PDF::Reader::Reference:0x00000007ed7298 @id=8585, @gen=0>, :Fcpdf2=>#<PDF::Reader::Reference:0x00000007ed6500 @id=8588, @gen=0>, :Fcpdf3=>#<PDF::Reader::Reference:0x00000007ed60f0 @id=8590, @gen=0>}, :ProcSet=>#<PDF::Reader::Reference:0x00000007ed51a0 @id=4, @gen=0>}, :MediaBox=>[0, 0, 594, 792], :CropBox=>[0, 0, 594, 792], :Rotate=>0, :Contents=>[#<PDF::Reader::Reference:0x000000077fa0d8 @id=18, @gen=0>, #<PDF::Reader::Reference:0x000000077f9e30 @id=19, @gen=0>]} 
```

**Comment by yob** [comment]
Thanks for reporting this, and apologies for taking so long to review it.

Unfortunately it will be very difficult to investigate further without a copy of the sample PDF. I'm going to close this for now, but feel free to re-open it if additional information is available.
