### ISSUE TITLE
Does not return the text written certain font

### ISSUE THREAD

**Issue by flaminestone** [yob/pdf-reader#136]
Hello. I can't to parse some pdf files. These have some text written fonts such as 
https://drive.google.com/folderview?id=0BzDb0f_tVYoAVFFual9KS0VEbjg&usp=sharing
After parse i got text = "", and font = nil.
I checked 200 different fonts and only those have caused problems
   pdf-reader version  1.3.3

```
PDF::Reader.open("GulimChe.pdf") do |reader|
    reader.pages.each do |page|
        font = page.fonts[:F1][:BaseFont].to_s 
        text = page.text
    end
end
```

**Comment by aprescott** [comment]
I think I'm seeing this problem (or something like it?), for Raleway SemiBold and Raleway Regular. When using either of those, `reader.pages.map(&:fonts)` returns an array of all `{}` values, and `pages.map(&:text)` has all empty strings. It seems as if those typefaces lead to the text acting as if it's completely missing. Switching to an unspecified typeface value of "sans-serif" (through `font-family: sans-serif;` with a HTML -> PDF generator) makes the text available.

**Comment by yob** [comment]
Apologies for taking so long to review this - it seems the sample file is no longer available.

I'm going to close the issue for now, but feel free to re-open it with additional info if required.

**Comment by flaminestone** [comment]
[Cambria Math.pdf](https://github.com/yob/pdf-reader/files/774341/Cambria.Math.pdf)
[Dotum.pdf](https://github.com/yob/pdf-reader/files/774343/Dotum.pdf)
[DotumChe.pdf](https://github.com/yob/pdf-reader/files/774344/DotumChe.pdf)
[GulimChe.pdf](https://github.com/yob/pdf-reader/files/774342/GulimChe.pdf)
It it files from issue.

**Comment by yob** [comment]
Thanks for the sample files @flaminestone.

I've checked `Cambria Math.pdf` and `GulimChe.pdf`. Neither has a font in the page resources, and I suspect the tool that generated the files has converted the fonts to vector lines. If that's the case, then no tool will be able to extract the text.

Have you tried copying the text in adobe acrobat? I suspect that will have the same issue.
