### ISSUE TITLE
PDF does not contain EOF marker (PDF::Reader::MalformedPDFError)

### ISSUE THREAD

**Issue by som-poddar** [yob/pdf-reader#140]
I am trying to create a new PDF document from the `raw content` of another PDF (gist https://gist.github.com/som-poddar/8137c986b37e036444bc). Why do I keep on getting `find_first_xref_offset': PDF does not contain EOF marker (PDF::Reader::MalformedPDFError)`. I am using Mac OS-X

**Comment by GolfyMcG** [comment]
+1

**Comment by GolfyMcG** [comment]
@som-poddar - are you certain the PDF has any content? My problem, I've realized, is due to the lack of any content for the PDF.

**Comment by craineum** [comment]
+1 I am getting the same with with a PDF that has content.

**Comment by GolfyMcG** [comment]
I realized the problem for me was that there was a server side error when I
was generating the PDF that prevented the PDF from actually being rendered.
Ie. I had some sort of Ruby logic in the view that contained a syntax
error. An exception was raised but it didn't bubble up through the PDF so
the page would t be finished rendering and this EOF marker wouldn't be
produced.

**Comment by craineum** [comment]
@GolfyMcG I am running a test with capybara and selenium.  I can see the PDF in firefox as the test is running.  If I drop into byebug I can see the pdf in page.source.  Thanks for the reply, but I think mine is a different issue. :(  Would love it if I would just have to fix something server side.

**Comment by GolfyMcG** [comment]
I was able to render the PDF as well actually. I discovered the issue by
copying my work into an HTML document where the exception wasn't be covered
up. Certainly, this might be a different problem but I would see if you can
get the exact same code to render in HTML. If it works, then I have no idea
: /

**Comment by craineum** [comment]
Got it... When testing in capybara and not using the RackTest driver (like using selenium), the file was no longer actually being downloaded.  It was opening in the browsers PDF viewer, thus it was not a PDF.  Either switching to RackTest or using the browsers pdf viewer to test fixed this for me.

Thanks for the input!

**Comment by sandeepnagra** [comment]
+1 som-poddar

Let me know if you were able to find a solution to this problem.

**Comment by yob** [comment]
Thanks for this report. For reference, here is a copy of the referenced gist:

```ruby
require 'pdf/reader'

raw_string = ''
#INSTRUCTION: save it locally http://www.energy.umich.edu/sites/default/files/pdf-sample.pdf
filename = File.expand_path(File.dirname(__FILE__)) + '/pdf-sample.pdf'
PDF::Reader.open(filename) do |reader|
  reader.pages.each do |page|
    raw_string  = page.raw_content
    puts page.raw_content
  end
end

#check if 'raw_string' is Malformed PDF or not
PDF::Reader.new(StringIO.new(raw_string))
puts 'done'
```

Unfortunately, this approach won't work. `page.raw_content` will return the program that renders a page, but that's only a small part of what makes a valid PDF. There's a significant amount of additional data (fonts, images, metadata, etc) that needs to be included as well.

It looks like you might be trying to use `pdf-reader` to split a multi-page PDF into individual files? If so, unfortunately `pdf-reader` is not able to do that out of the box. You may need to find an alternative tool.

**Comment by gfx** [comment]
I found exactly the same error, now I use [origami](https://github.com/gdelugre/origami) to parse PDFs, which doesn't die on strange PDFs.

**Comment by djalmaaraujo** [comment]
@gfx I found an issue on origami saying that they don't support getting the page text in origami. What are you using to get the page content?

**Comment by andykallhoff** [comment]
If you are trying to test anything with the `raw_content` portion and you don't have or want to have an actual test.pdf file, you can use `stubs`. Using `minitest` and `mocha` you could do something along these lines:
```
CONTENT = ['one', 'two', 'three']

setup do
  pages = [OpenStruct.new(raw_content: CONTENT.join("\n"))]
  pdf_structure = OpenStruct.new
  pdf_structure.stubs(:pages).returns(pages)
  PDF::Reader.stubs(:new).returns(pdf_structure)
  @pdf = PDF::Reader.new
end

# now you should have your 'pdf' built out
# note: if you need more methods you can always stub them the same way as above

test 'whatever' do
  assert @pdf.pages.first.raw_content.include?('one')
end
```

For all you rspec-ers out there I found this, however *disclaimer* I have no idea how accurate it is: https://yob.id.au/2012/03/25/testing-pdf-content-in-ruby.html
