### ISSUE TITLE
Font size is always equal to 1

### ISSUE THREAD

**Issue by jeremypele** [yob/pdf-reader#141]
Hi,

I am running a step by step debug and I am noticing that no matter what the font size is equal to 1 (which is not the case at all), whatever pdf I input in.
set_text_font_and_size(:xx, 1)

Any idea?

Regards

**Comment by yob** [comment]
Thanks for this report.

Without further details, it's hard to guess what's going on.

The font size that's included in the content stream is modified by the current state of the page, so it's possible that although the stream says font size 1, the number is larger when the glyph is actually rendered. The `PageState` class implements some of the logic required to determine the real font size, and you might find it a useful read.
