### ISSUE TITLE
Text is extracted twice for all bolded characters

### ISSUE THREAD

**Issue by trejkaz** [yob/pdf-reader#143]
If the PDF contains fonts which don't have a bold variant but the document it was created from had specified them as bold, it looks like some PDF generators do this by printing each glyph twice, with the second one slightly to the right of the first.

I'm trying to write a test which confirms that the text "Name:" is present in the text, but as this text is bold in the PDF file, pdf-reader extracts the following:

```
N Na am me e: :
```

It is difficult to reverse this mangling back into the original text.

Bafflingly, on other such files I have seen it extract "Naame:" or "GUUID:" - so it isn't always duplicating every character.

**Comment by tmlee** [comment]
Think i have the same finding @trejkaz Were you able to figure a way to address this issue?

**Comment by trejkaz** [comment]
Nope. :(

I think that technically it is the fault of the generation software. If I print bold text using Safari and Apple's PDF printer, *that* one bolds the characters still (i.e., it's still doubling the characters visually) but when you get the text from it, it only gets it once (suggesting that they know a way to mark a character as not part of the text.)

**Comment by yob** [comment]
Unfortunately the layout algorithm in `PageLayout` is more simplistic than I'd like.

My time is pretty limited these days, but I'd happily review patches that attempt to detect and ignore duplicate characters that are positioned close to each other.

**Comment by giaunvNUS** [comment]
Could you please fix this one @yob ? It can help very much :)
