### ISSUE TITLE
With 1.3.3: undefined method `[]' for #<PDF::Reader::Reference:0x2c851e0 @id=32, @gen=0> 

### ISSUE THREAD

**Issue by bback** [yob/pdf-reader#144]
After installing 1.3.3 I can no longer use the library. It always fails with the following error:

C:/Tools/ruby/lib/ruby/gems/2.2.0/gems/pdf-reader-1.3.3/lib/pdf/reader/page_layout.rb:17:in `initial
ize': undefined method`[]' for #<PDF::Reader::Reference:0x2c851e0 @id=32, @gen=0> (NoMethodError)
        from C:/Tools/ruby/lib/ruby/gems/2.2.0/gems/pdf-reader-1.3.3/lib/pdf/reader/page_text_receiv
er.rb:49:in `new'
        from C:/Tools/ruby/lib/ruby/gems/2.2.0/gems/pdf-reader-1.3.3/lib/pdf/reader/page_text_receiv
er.rb:49:in`content'
        from C:/Tools/ruby/lib/ruby/gems/2.2.0/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:76:in `t
ext'
        from C:/WORK/pdf-test.rb:17:in`<main>'

**Comment by bback** [comment]
Note: Up to line 17 my code basically looks like this (comments removed):

require 'pdf-reader'
reader = PDF::Reader.new(ARGV[0])
lines = reader.pages[0].text.split(/$/)

**Comment by salazareddie** [comment]
@bback Was having the same problem. Solved with a bundle update pdf-reader. Looks like I was using ttfunk 1.2.0 and upgrading it to 1.2.2 fixed the issue.

**Comment by salazareddie** [comment]
@bback also fixed the issue by doing this in my gemfile
```
gem 'pdf-reader', :git => 'git://github.com/yob/pdf-reader.git'
```

**Comment by yob** [comment]
It sounds like this might be resolved in newer releases. I'll close the issue for now, but feel free to re-open if more information becomes available.
