### ISSUE TITLE
Text from PDFs with Identity-H encoded fonts sometimes results in only squares

### ISSUE THREAD

**Issue by RST-J** [yob/pdf-reader#145]
First thanks for this great library.
Unfortunately we sometimes have issues with the text extraction where the entire text results in squares:

```
▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯
▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯
▯▯▯▯▯▯▯▯▯▯▯
▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯▯
...
```

In Acrobat Reader, the text is shown correctly and it is also possible to copy text from there.
As I'm not familiar with the deeper details of the PDF spec and how it handles fonts, I can only report this issue.
I have put an affected [PDF](http://www.peschla.net/pdf_reader/identity_h.pdf) on my web server so one can reproduce the problem.
In this PDF all fonts are embedded subsets of type TrueType (CID) and have Identity-H encoding.

Can anyone help or has a hint where to dig in?

**Comment by nneal** [comment]
Having similar issue. However, we get `*** NoMethodError Exception: undefined method `unfiltered_data' for :"Identity-H":Symbol` when trying to do `page.text`

**Comment by frugardc** [comment]
Still seeing this issue in certain documents...

    undefined method `unfiltered_data' for :\"Identity-H\":Symbol"

**Comment by yob** [comment]
Are you able to share the full stack trace and/or a PDF that triggers the
exception?

**Comment by vjustov** [comment]
I'm seeing this issue with [this PDF](https://github.com/yob/pdf-reader/files/287786/A_-_PRESIDENCIAL_BOLETIN_9.pdf). All the output is squares even though I can open and copy from the pdf.

**Comment by yob** [comment]
#197 has resolved the issue reported by @RST-J and @vjustov - the text can be extracted from both sample files using the master branch.

Unfortunately I don't have sample files for the exception reported by @nneal and @frugardc, so haven't been able to re-create it. If any additional info on the exceptions is available, please open a new ticket.
