### ISSUE TITLE
override == so two readers initialized on the same pdf file are equal

### ISSUE THREAD

**Issue by fakeleft** [yob/pdf-reader#147]
I'd like to compare 2 PDF::Reader instances, and assume == should return true if they were created from the same pdf file. Should this not be the case?

**Comment by siaw23** [comment]
I understand your logic. But the `object_id` for two different instances of PDF::Reader differs, hence the result of `==` returning `false`.

**Comment by yob** [comment]
Thanks for the suggestion, but I'm not convinced this is something I want to include. `pdf-reader` supports loading files from memory (not just disk), so implementing this would probably require a byte-level comparison of the underlying data. It's certainly possible, but I'd like to hear more about the possible use cases before adding code.

Feel free to re-open the issue and continue the discussion :)
