### ISSUE TITLE
two instances of different object ids.

### ISSUE THREAD

**Issue by siaw23** [yob/pdf-reader#150]
I instantiated 2 objects of PDF::Reader from the same file expecting the `object_id` to be the same, is there a reason they differ?

**Comment by yob** [comment]
Generally in ruby we'd expect the `object_id` of be different even if two objects are equal:

```ruby
irb(main):001:0> "foo".object_id
=> 47153180182320
irb(main):002:0> "foo".object_id
=> 47153180209720
irb(main):003:0> "foo".object_id
=> 47153180261740
```
