### ISSUE TITLE
Travis errors

### ISSUE THREAD

**Issue by koriroys** [yob/pdf-reader#153]
Parallel (dependency of cane) requires ruby 1.9.3 or greater, so travis builds of ruby 1.8.7 & 1.9.2 just fail.

**Comment by yob** [comment]
I'd be happy to drop support for < 1.9.3 on master I think, they're quite rare these days

**Comment by koriroys** [comment]
closed  by 263ee2ce20fc2cdb724a2d78dc6319e048aafb46
