### ISSUE TITLE
Undefined method `to_i` for HASH when trying to read page

### ISSUE THREAD

**Issue by bhayani** [yob/pdf-reader#159]
I have a PDF that is causing the following error when I try to access the first page.

```
NoMethodError: undefined method `to_i' for #<Hash:0x00000011481000>
from /var/rails/gumroad/shared/bundle/ruby/2.2.0/gems/pdf-reader-1.3.3/lib/pdf/reader/object_hash.rb:73:in `[]'
```

Here is my code.

```
reader = PDF::Reader.new(original_pdf_file.path)
reader.page(1)
```

Surprisingly, `reader.page_count` works fine, but `reader.pages` gives the same error.

Here is a link to the PDF causing this error: https://www.dropbox.com/s/c24n12634hhaojv/trouble_maker.pdf?dl=0

**Comment by yob** [comment]
Thanks for reporting this, and apologies for taking so long to look into it.

This is an interesting case, as the PDF slightly violates the spec, and I noticed that poppler/evince is unable to open it. Acrobat *does* open it though, and the fix is trivial so I've addressed it in #203.
