### ISSUE TITLE
Is decomposition of layers possible?

### ISSUE THREAD

**Issue by KillaPL** [yob/pdf-reader#167]
Hi

If I have a pdf, about which I know it has just one page, contains a set of layers, and there is color data associated with each layer, would it be possible to extract those layers and, for example, save them to disc as tiff or jpg files? Or to database as some sort of text file, which I could then read for further processing?

**Comment by yob** [comment]
It would be technically possible, but `pdf-reader` doesn't provide anything out of the box that meets your needs.

You'd have to write a custom receiver class that processes each page (see `PDF::Reader::Page#walk`), renders the bits you care about and writes them to your disk or database.
