### ISSUE TITLE
PDF::Reader hangs on corrupted / invalid pdfs. 

### ISSUE THREAD

**Issue by gamba** [yob/pdf-reader#176]
here an example of an invalid pdf found on the internet:

```
p = open("https://www.admin.ch/opc/de/classified-compilation/19983439/201210010000/172.010.1.pdf") 
reader = PDF::Reader.new(p)
```

.new method never returns, i would expect an exception.

**Comment by yob** [comment]
Thanks for reporting this - I've tracked down the issue and prepared a fix in 63257a2
