### ISSUE TITLE
Finding Attachments inside PDF

### ISSUE THREAD

**Issue by sriram15690** [yob/pdf-reader#179]
I have a pdf with attachments inside. (I have attached the same to issue as well).

Using pdf-reader gem, how can i do the following: 
1. Detect if a pdf has attachments
2. If it has, how to find the details of the attachments.

If pdf-reader cannot perform this action, may i know any other gem/library which can get this information. 
[PDFWithFileAttachmentAnnotation.pdf](https://github.com/yob/pdf-reader/files/393070/PDFWithFileAttachmentAnnotation.pdf)

**Comment by yob** [comment]
Here's a very basic script that will tell you if a PDF page has annotations, and some basic details about them:

```ruby
require 'pdf-reader'

PDF::Reader.open("PDFWithFileAttachmentAnnotation.pdf") do |pdf|
  page = pdf.page(1)
  puts "Has Annotations?"
  puts page.attributes.key?(:Annots)
  puts
  Array(page.attributes[:Annots]).each do |annot|
    data = pdf.objects.deref(annot)
    puts data.inspect
  end
end
```

Section 12.5 of the [pdf spec](http://www.adobe.com/devnet/pdf/pdf_reference.html) has more details on annotations. Section 12.5.6 is particularly interesting - it lists the various types of annotations and how they're stored in a PDF.

**Comment by dankimio** [comment]
Is it possible to extract text that is associated with a given annotation?

**Comment by yob** [comment]
I'm not super familiar with Annotations, but it should be. pdf-reader doesn't have any helpers to make it nice though.

The above code snipped doesn't show any annotation text?

**Comment by dankimio** [comment]
I'm getting `PDF::Reader::Reference` instances, but I'm not sure how to extract text using those.

```ruby
Array(page.attributes[:Annots]).each do |annot|
  data = pdf.objects.deref(annot)
  puts data.inspect
  # [#<PDF::Reader::Reference:0x000000012400e4c8 @id=357, @gen=0>, #<PDF::Reader::Reference:0x000000012400de88 @id=356, @gen=0>]
end
```

**Comment by yob** [comment]
If you use the ! version of deref (`deref!`), it should resolve that references recursively.
