### ISSUE TITLE
UTF-8 conversion won't work for PDF files OCRed using Adobe ClearText

### ISSUE THREAD

**Issue by retrography** [yob/pdf-reader#180]
I get gibberish when I run `PDF::Reader::PageState.current_font.to_utf8(glyph_code)` instance method on each of the glyph codes returned by `PDF::Reader::PageState.current_font.unpack(string)`. I am try to convert texts from Adobe ClearText OCRed documents. [Here](https://dl.dropboxusercontent.com/u/1464091/sample.pdf) is an example PDF file that can be used to reproduce the issue.

**Comment by yob** [comment]
Thanks for reporting the issue. I tested text extraction from the sample file in both Acrobat 10 and evince, and neither tool was able to extract readable characters.

Is it possible there's an issue with the PDF itself rather than with `pdf-reader`?

**Comment by retrography** [comment]
I have note been able to recover the text either. This is the case of many
different Acrobat-converted PDFs I have, and may be a result of some file
operation at some point in time. In any case, please close the issue. This
is either a file corruption issue or it is so rare that it does not deserve
attention, unless corroborated by other users.


On January 3, 2017 at 4:10:05 PM, James Healy (notifications@github.com)
wrote:

Thanks for reporting the issue. I tested text extraction from the sample
file in both Acrobat 10 and evince, and neither tool was able to extract
readable characters.

Is it possible there's an issue with the PDF itself rather than with
pdf-reader?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yob/pdf-reader/issues/180#issuecomment-270135155>, or mute
the thread

**Comment by yob** [comment]
Cheers
