### ISSUE TITLE
Styling Loss When Rendering the parsed pdf file to my view

### ISSUE THREAD

**Issue by vrouth** [yob/pdf-reader#182]
I have a pdf file with with bold heading, tables, etc.
When i'm rendering the parsed file through pdf-reader into my html, all the texts are having same font-weight. Also, loss of table structures happening. Can you please help me out...what am i doing wrong??
My code is -->

In my Jobs controller, i have a method 
`def viewjobapplication`
`io = open('http://s3-ap-southeast-1.amazonaws.com/static.referhire.com/rhdoc/res/prfl/8e3c37921f1e451cc84fbd76257d95985b154d21/Guruprasad_G_SAP_BO_-_Copy.pdf')`
`@reader = PDF::Reader.new(io)`
`end`
and in my viewjobapplication.html.erb file, i'm accessing it like this way -->
`<% @reader.pages.each do |p| %><div style="background:#fff;padding:5px;border:1px solid #424242;"><pre><%= p %></pre></div><%end%>`

i've attached the images also for original file and the rendered view in browser...please have a look
![original file](https://cloud.githubusercontent.com/assets/16283933/18671636/79365676-7f62-11e6-9598-4fd56fc73768.png)
![rendered html view](https://cloud.githubusercontent.com/assets/16283933/18671688/a16a1844-7f62-11e6-923c-068c242dc128.png)

**Comment by yob** [comment]
Thanks for filing this issue.

`pdf-reader` is not intended to be a complete PDF to HTML conversion tool, so it's not surprsing that the PDF tables and formatting are lost. You may need to look for another tool that meets your needs.
