### ISSUE TITLE
How I can add image in footer of exiting pdf file.

### ISSUE THREAD

**Issue by udkumar** [yob/pdf-reader#201]
I really appreciate if anyone can guide me below:

- How I can add image inside footer of existing pdf?

- How I can show user only limited page? Like User has pdf file which has 100 page, I want to show 20 page only.

I do not need exact code, Just I want to know approx idea.

Thanks

**Comment by yob** [comment]
Hi,

pdf-reader does not provide an API for modifying PDF files, so unfortunately I think it won't meet your needs.
