### ISSUE TITLE
Is raw_content unique for pdf files that doesn't look the same?

### ISSUE THREAD

**Issue by mmustala** [yob/pdf-reader#212]
Hi.

I want to generate a checksum from a pdf file so that I can find which pdf files are identical. Would the raw_content of the pages be a good data to calculate the checksum from?

I can confirm that two identical looking pdf files have the same raw_content. But is it also so that no different looking pdf files could have the same raw_content?

**Comment by yob** [comment]
You'll probably find that a checksum is a reasonable approximation of uniqueness, but it's not guaranteed. 

Some data (fonts, images, etc) is stored in the header of each page and only referenced by name in raw_content. That means in theory you could have identical raw_content that uses different fonts or images, resulting in a visually different file.
