### ISSUE TITLE
some errors with version 2.0 (and files are valid)

### ISSUE THREAD

**Issue by MathieuDerelle** [yob/pdf-reader#213]
I have several PDFs that are generating some errors with this gem but are correctly handled by other programs.

- First, a PDF giving an error that is neither MalformedPDFError or UnsupportedFeatureError:
[20170212-1018-2831-314589-1.pdf](https://github.com/yob/pdf-reader/files/868707/20170212-1018-2831-314589-1.pdf)

```ruby
p = PDF::Reader.new(path)
p.pages.first.text
# TypeError: no implicit conversion of nil into String
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:237:in `prepare_inline_token'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:177:in `block in prepare_tokens'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:172:in `times'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:172:in `prepare_tokens'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/buffer.rb:118:in `token'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/parser.rb:134:in `pdf_name'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/parser.rb:37:in `block in <class:Parser>'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/parser.rb:76:in `call'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/parser.rb:76:in `parse_token'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:144:in `content_stream'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:111:in `walk'
# /Users/mathieu/.rvm/gems/ruby-2.2.5/gems/pdf-reader-2.0.0/lib/pdf/reader/page.rb:81:in `text'
# (pry):17:in `__pry__'
```

- PDF::Reader::MalformedPDFError: xref stream not found when expected
[20170323-1505-6657-314380-1.pdf](https://github.com/yob/pdf-reader/files/868709/20170323-1505-6657-314380-1.pdf)

- PDF::Reader::MalformedPDFError: PDF malformed, expected 5 but found 4 instead
[20170322-1634-2447-323309-1.pdf](https://github.com/yob/pdf-reader/files/868712/20170322-1634-2447-323309-1.pdf)

- PDF::Reader::MalformedPDFError: PDF malformed, expected 5 but found 0 instead
[reformed.pdf](https://github.com/yob/pdf-reader/files/868715/reformed.pdf)

Hope you can improve this gem with that

**Comment by virusman** [comment]
How did you generate these files?
I checked 20170322-1634-2447-323309-1.pdf - it has a broken xref table. Most PDF viewers silently fix that, though.

**Comment by MathieuDerelle** [comment]
they are created by a scanner

**Comment by neatyyue** [comment]
I came across the same issue with a 2-page pdf wherever the first page gave me error when trying to read the text.

**Comment by yob** [comment]
Thanks for providing these. I've confirmed the first 3 files parse correctly in v2.9.0, however the final file (reformed.pdf) still errors.

**Comment by yob** [comment]
> however the final file (reformed.pdf) still errors

interesting. The xref table in this file has a slightly wrong byte offset for object 5, which is definitely "Malformed". Other readers must be able to compensate for this error - for example, I notice this message in the console when I open it in Firefox and yet it opens correctly:

```
Warning: XRef.parse - Invalid "Root" reference: "XRefEntryException: Bad (uncompressed) XRef entry: 5R".
```
