### ISSUE TITLE
undefined method '[]' on PDF::Reader::Reference

### ISSUE THREAD

**Issue by rjhancock** [yob/pdf-reader#253]
Using version 1.3.3 (app is using ruby 1.8.7 at the moment) and getting this error anytime I try to access the text of a PDF. Same when using the pdf_text binary.

I've attached the smaller of the files needing to be opened.

[Status of Bills-Cumulative.pdf](https://github.com/yob/pdf-reader/files/1278616/Status.of.Bills-Cumulative.pdf)

When trying from a console:

NoMethodError: undefined method `[]' for #<PDF::Reader::Reference:0x112364c10 @gen=0, @id=3>
	from /Users/rjhancock/.rvm/gems/ruby-1.8.7-head@spidey/gems/pdf-reader-1.3.3/lib/pdf/reader/page_layout.rb:17:in `initialize'
	from /Users/rjhancock/.rvm/gems/ruby-1.8.7-head@spidey/gems/pdf-reader-1.3.3/lib/pdf/reader/page_text_receiver.rb:49:in `new'
	from /Users/rjhancock/.rvm/gems/ruby-1.8.7-head@spidey/gems/pdf-reader-1.3.3/lib/pdf/reader/page_text_receiver.rb:49:in `content'
	from /Users/rjhancock/.rvm/gems/ruby-1.8.7-head@spidey/gems/pdf-reader-1.3.3/lib/pdf/reader/page.rb:76:in `text'
	from (irb):118
	from :0

**Comment by rjhancock** [comment]
Looking further into it, it seems that the objects aren't be dereferenced like they should. Still working through it though.

**Comment by rjhancock** [comment]
I found a solution but not sure why it's an issue with this file. In the Page class for attributes, I added a loop over the hash to deref the values a second time and it solved my issue.

Just not sure if this is a wider issue or not.

**Comment by jamesdabbs** [comment]
Hitting the same issue here. For concreteness, `page.attributes[:MediaBox]` is an `Array` for some documents and a `PDF::Reader::Reference`. If it's the latter, `box = page.objects.deref box` fixes it.

**Comment by yob** [comment]
Thanks for reporting this.

The specific issue with pdf_text in version 1.3.3 was addressed in (7871128cb), which is included from 1.4.0 upwards - sorry!

The generic issue with custom code that calls `PDF::Reader::Page#attributes` and receives a result where `MediaBox` can be an indirect object has been discussed a bit in #263, and for now the officially supported solution is the one recommended by @jamesdabbs:

> For concreteness, `page.attributes[:MediaBox]` is an Array for some documents and a PDF::Reader::Reference. If it's the latter, `box = page.objects.deref box` fixes it

You may even want to use `deref!` (eg `box = page.objects.deref!(box)`) to be completely sure that the `MediaBox` array you get back is an Array with numbers.

**Comment by rjhancock** [comment]
Thanks. The patch I put in place is similar for what is currently needed. Working on getting the code base up to a point that I can finally get it up to Ruby 2+. Been 3 years in the making (along with all the other issues that have come up) and slowly making progress.
