### ISSUE TITLE
How to extract text from Prawn "stamp"?

### ISSUE THREAD

**Issue by henrik** [yob/pdf-reader#268]
The attached example.pdf was generated with `create_stamp` and `stamp` in the Prawn PDF library.

[example.pdf](https://github.com/yob/pdf-reader/files/1603599/example.pdf)

Visually, it contains the strings "One" (as a stamp) and "Two" (as regular text).

But if I try to extract that text with pdf-reader, the "One" is not in there as a continuous string. Is there any way to get that? This seemed to work as expected (could get that string) with pdf-reader 1.3.3.

This is the text I get out:

``` ruby
reader = PDF::Reader.new("/Users/henrik/Downloads/example.pdf")
reader.pages.map { |page| page.text }
# => ["Two\n\n\n\n\n       n e\n      O"]
```

My use case is to be able to verify inclusion of these stamps in specs for PDFs generated with Prawn, via pdf-inspector: https://github.com/prawnpdf/pdf-inspector/issues/25#issuecomment-355290330

**Comment by yob** [comment]
prawn stamps are implemented using XObjects, and pdf-reader definitely parses them when building each page.

The complication is that `PDF::Reader::Page#text` attempts to map the page text onto a 2d plain text page, which can't accurately represent diagonal text.

The characters in `One` are snapping to the nearest regular x,y position on the plain text "page".

It's unlikely that we'll change `PDF::Reader::Page#text` to handle this situation better - there's no reasonable way to meet everyone's expectations with text layout. The method delegates to a class (`PDF::Reader::PageTextReceiver`) though. If you wanted an alternative text extraction algorithm with different tradeoffs it'd be quite feasible to duplicate that class into your own project and modify it.

> This seemed to work as expected (could get that string) with pdf-reader 1.3.3.

That's interesting. pdf-reader 1.x used the same basic approach when extracting plain text, but there's been a number of small tweaks to font size and positioning calcs. It's possible the changes were enough to move the `O` to the adjacent position on the plain text "page" - sorry!

**Comment by henrik** [comment]
@yob Thank you so much for that thorough answer! Appreciate it and completely understand it's unlikely to be "fixed"/changed. I may play with `PageTextReceiver` and will hopefully report back here if I come up with something that may be helpful to someone else.

**Comment by andi-dev** [comment]
@henrik it's been almost a year, but I've been wondering if you came up with something?

**Comment by henrik** [comment]
Hey @andi-dev. Afraid not - I think maybe I settled for checking small substrings.
