### ISSUE TITLE
Problems reading landscape pdf files

### ISSUE THREAD

**Issue by ninorachota** [yob/pdf-reader#271]
I discovered that pdf files that are orientated as landscape are weirdly read by the pdf-reader. In portrait its just the normal left to right, top to bottom, but in landscape it reads from left bottom to left top and then it reads the next line. That means that the reader uses a fixed point on the document, that gets rotated 90 degrees counter clockwise when a document is in landscape.

**Comment by ninorachota** [comment]
Due to privacy reason I'm not eligable to send a file on which it happens. I can send you the output I get when using it.
ThVu11W5e2d1102-D0A9YLMLoAnX08
the actual output should be Thu11, Wed10, AV521, 2-DAY, LAX and Mon08
As you can see the data is oddly giving back. This comes from a document that has a table in it. Could it be that the table is causing problems.

**Comment by yob** [comment]
A table shouldn't cause issues, but it's hard to be sure without seeing the file.

I'm pretty confident the issue will be in processing the way the file was generated, rather than the fact that it's landscape.

**Comment by AsrorWali** [comment]
@ninorachota It's a wild guess. But it might be possible that the gem doesn't get the correct font_width so it messes up the sentence. If you tried to read the same pdf with a ruby gem that doesn't recreate the format of the pdf or a python package. Do you still get this issue ?

**Comment by ninorachota** [comment]
I was able to fix it using ghostscript

**Comment by AsrorWali** [comment]
@ninorachota Interesting... What excatly did you do with ghostscript if i might ask ?

**Comment by ninorachota** [comment]
I just used ghostscript to create a new version of the pdf file. I guess there was something wrong when the original file was created.

**Comment by zealot128** [comment]
I've created an issue with example code in #339 on how to reprocess with ghostscript

**Comment by yob** [comment]
Without a sample file it's hard to be sure, however there's a very high chance the positioning issues described here are addressed by the fixes I'm working on for #397. Hopefully I'll land them on main in the next few days and we can resolve this issue at the same time.
