### ISSUE TITLE
not reading metadata

### ISSUE THREAD

**Issue by jrochkind** [yob/pdf-reader#274]
I have a PDF I created with prawn, and added metadata tags. 

When I open it up in MacOS preview, and do a 'get info', my metadata is there, it shows it. 

But when I open it up with PDF::Reader, and look at `reader.metadata`, I get `nil` back.

**Comment by yob** [comment]
That's surprising - many of the test files used to develop pdf-reader were generated by prawn.

Are you able to share a sample PDF and code that demonstrates the issue?
