### ISSUE TITLE
scanned pdf file 

### ISSUE THREAD

**Issue by prathip111** [yob/pdf-reader#277]
I have an issue when I read scanned pdf document it should not read its return empty ""... can you help it?

**Comment by yob** [comment]
Hi @prathip111,

Depending on the scanning software that created the PDF, the file may not have text data embedded in it. If that's the case, it may only have a copy of the scanned document as an image and pdf-reader doesn't include any support for recogising characters in a scanned image.

**Comment by prathip111** [comment]
Hi @yob 
   Ohhh okay.. Thanks for your response...
