### ISSUE TITLE
Raw Content format? 

### ISSUE THREAD

**Issue by nacu4** [yob/pdf-reader#282]
I'm trying to extract some data and everything seems to be running correctly except that "page.text" doesn't actually find anything from the PDF. When I comment out raw_content, I get nothing. When I comment out text, I get tons of data from raw_content. The problem is, raw content isn't in a readable format, so I'm wondering how I can format it in a way that the data is actually helpful. Any ideas? I'm fairly new, so happy to share other information. 

```
#!/usr/bin/env ruby
# coding: utf-8

require 'rubygems'
require 'pdf/reader'

filename = File.expand_path(File.dirname(__FILE__)) + "/Catalog.pdf"
fname = "test.txt"
somefile = File.open(fname, "w")

PDF::Reader.open(filename) do |reader|
#  puts reader.info.inspect
#  puts reader.metadata.inspect

 reader.pages.each do |page|
      #somefile.puts page.fonts
      #somefile.puts page.text
      somefile.puts page.raw_content
    end
end
```

This is the screenshot of the PDF.  
![catalog](https://user-images.githubusercontent.com/22282824/45394793-5c92d680-b5e7-11e8-8d71-f3be93ba9587.JPG)

This is the output in the text file. 
![output](https://user-images.githubusercontent.com/22282824/45394792-5c92d680-b5e7-11e8-8358-6910d2b6297b.JPG)

**Comment by yob** [comment]
It's hard to by 100% sure without examining the PDF file, but my guess is all the text on the page is rendered using graphics operations (eg. lines on the page) rather than text operations.

If my guess is right,  unfortunately pdf-reader will be unable to extract text using the `Page#text` method.
