### ISSUE TITLE
input must be an IO-like object or a filename

### ISSUE THREAD

**Issue by Faisal-nfl** [yob/pdf-reader#285]
I tried [extract_images.rb](https://github.com/yob/pdf-reader/blob/master/examples/extract_images.rb)
When I try this 
filename = File.expand_path(File.dirname(__FILE__)) + "/public/abc.pdf"
extractor = ExtractImages::Extractor.new

it says "input must be an IO-like object or a filename"

**Comment by yob** [comment]
Hi,

Can you include the code where you call `PDF::Reader.new` or `PDF::Reader.open`? That probably the line where the issue is.

**Comment by encoreshao** [comment]
Hi, @Faisal-nfl ,

The same error occurred in my project. Finally, I found that I was using the wrong file path. I think maybe you should double check the file path in the code.

Encore

**Comment by yob** [comment]
I'm going to close this issue, but if you have further information please feel free to re-open it.
