### ISSUE TITLE
MalformedPDFError related to xref location

### ISSUE THREAD

**Issue by rjhancock** [yob/pdf-reader#286]
I've tried several different ways of opening a PDF downloaded from a state legislative site. It opens fine in browsers and Preview on macOS. When reviewing the file in VSCode, it appears fine with no issues. When trying to open the source file from the rails console, I get:

> PDF::Reader::MalformedPDFError (xref table not found at offset 63088 (?D??ȷA?"? != xref))

While trying to open versions where I've printed and/or exported from Preview, I get the following error:

> LocalJumpError (no block given (yield))

Rails: 5.2.2
PDF Reader: 2.2.0
Ruby 2.6.0

[export.pdf](https://github.com/yob/pdf-reader/files/2734662/export.pdf)
[print.pdf](https://github.com/yob/pdf-reader/files/2734663/print.pdf)
[source.pdf](https://github.com/yob/pdf-reader/files/2734664/source.pdf)

---
I've been going back and forth on this and am still perplexed as to what is going on. I do see the XRef table in the original PDF but not sure why it can't find it. Only other data I've found on the file is that it was made with OpenOffice 3.1 which I don't think helps anything.

**Comment by yob** [comment]
I can reproduce the error on my laptop:

```
$ ruby -Ilib bin/pdf_text source.pdf 
Traceback (most recent call last):
        7: from bin/pdf_text:9:in `<main>'
        6: from bin/pdf_text:9:in `new'
        5: from /home/jh/git/pdf-reader/lib/pdf/reader.rb:117:in `initialize'
        4: from /home/jh/git/pdf-reader/lib/pdf/reader.rb:117:in `new'
        3: from /home/jh/git/pdf-reader/lib/pdf/reader/object_hash.rb:45:in `initialize'
        2: from /home/jh/git/pdf-reader/lib/pdf/reader/object_hash.rb:45:in `new'
        1: from /home/jh/git/pdf-reader/lib/pdf/reader/xref.rb:61:in `initialize'
/home/jh/git/pdf-reader/lib/pdf/reader/xref.rb:117:in `load_offsets': xref table not found at offset 63088 (DA" != xref) (PDF::Reader::MalformedPDFError)
```

If you inspect the raw pdf, I think the problem is the line near the top starting with `%lwb360metadata`. If I remove that line, then the xref tables starts newar offset  63088 like the trailer claims.

pdf-reader only makes some very basic attempts to detect  cases where the files is offset by a consistent number of bytes due to extra junk at the top of the file. My guess is the other applications you've tested with are doing a better job at that.

**Comment by rjhancock** [comment]
Hmm... If I remove the metadata tag and try via the pdf_text command I get the following:

```
PDF::Reader::MalformedPDFError: PDF malformed, expected 22 but found 2 instead
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/gems/pdf-reader-2.2.0/lib/pdf/reader/error.rb:46:in `assert_equal'
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/gems/pdf-reader-2.2.0/lib/pdf/reader/parser.rb:98:in `object'
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/gems/pdf-reader-2.2.0/lib/pdf/reader/object_hash.rb:85:in `[]'
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/gems/pdf-reader-2.2.0/lib/pdf/reader/object_hash.rb:99:in `object'
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/gems/pdf-reader-2.2.0/lib/pdf/reader.rb:253:in `root'
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/gems/pdf-reader-2.2.0/lib/pdf/reader.rb:137:in `page_count'
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/gems/pdf-reader-2.2.0/lib/pdf/reader.rb:180:in `pages'
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/gems/pdf-reader-2.2.0/bin/pdf_text:11:in `<top (required)>'
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/bin/pdf_text:23:in `load'
  /Users/rjhancock/.rvm/gems/ruby-2.6.0@Spidey/bin/pdf_text:23:in `<top (required)>'
```

which tells me it's most likely a proper corrupted PDF. Thoughts?

**Comment by rjhancock** [comment]
Went a bit further and tested against HexaPDF as well (client wanted this resolved on Friday so tried several options), I can now confirm via PDFReader and Hexa that the source PDF is corrupt. Thanks for helping confirm this.
