### ISSUE TITLE
How to extract URLs / links from PDF?

### ISSUE THREAD

**Issue by sscirrus** [yob/pdf-reader#287]
I've been trying to identify hyperlinks in PDFs, but when I use `page.text`, I only capture links that are shown in the text itself.

Example 1, this works: http://www.google.com
Example 2, this doesn't work: [Google](http://www.google.com)

How can we use pdf-reader to capture all links?

**Comment by yob** [comment]
There's some discussion on the google group, so I might close this with a pointer there: https://groups.google.com/d/msg/pdf-reader/Wbq2qrBU7LA/rNv8ZNxbEgAJ
