### ISSUE TITLE
[feature request] toggle option on dedup feature

### ISSUE THREAD

**Issue by MathieuDerelle** [yob/pdf-reader#306]
would love to have a toggle option

taking ~40 seconds to read a 2 page PDF is annoying

**Comment by yob** [comment]
40 seconds to read 2 pages definitely doesn't sound reasonable.

That's a larger impact than I saw in my testing, but I guess it does depend on the specific file. If it's possible, I'd love to run some benchmarks with your file so I can understand why the impact is so high.

I can accept the file privately if that's helpful - james - at - yob - id - au

**Comment by MathieuDerelle** [comment]
I've sent you some examples via mail

**Comment by yob** [comment]
Thanks @MathieuDerelle.

I'm still open to adding an option to toggle the overlapping detection, however after looking at the files you sent I've opened two other issues that will get the text rendering time for your file back down about a second. 

If we can hit that kind of performance, will you still need the toggle?

**Comment by yob** [comment]
OK, I've merged those two fixes. Here's the text extraction times for one of the files you sent me, across several versions of pdf-reader.

Master is still x3 slower than the v2.2.1 release, but many, many times faster than the v2.3.0 release.

## v2.2.1

```
$ time ruby -Ilib bin/pdf_text slow-text.pdf > /dev/null

real    0m0.433s
user    0m0.412s
sys     0m0.024s
```

## v2.3.0

```
$ time ruby -Ilib bin/pdf_text slow-text.pdf > /dev/null
real    1m21.716s
user    1m21.606s
sys     0m0.057s
```

## master

```
$ time ruby -Ilib bin/pdf_text slow-text.pdf > /dev/null
real    0m1.326s
user    0m1.297s
sys     0m0.027s
```

**Comment by MathieuDerelle** [comment]
thanks for the update

with this kind of perf, a toggle is not needed anymore

I have to update my code now :\ 
I was already accommodating for those kind of duplicates
things like `/TT?OO?TT?AA?LL? AA? PP?AA?YY?EE?RR?/` :D

**Comment by MathieuDerelle** [comment]
I've benchmarked all the PDFs I have with this code : 
```
task :benchmark do
  require 'benchmark'

  Benchmark.bmbm do |x|
    Dir['samples/**/*.pdf'].each do |file_path|
      PDF::Reader.new(file_path).pages.each_with_index do |page, idx|
        x.report(format('%-90s (page %i)', file_path, idx + 1)) { page.text }
      end
    end
  end
end
```

most of the pages are read in less than a second
```
...
samples/gedimat/augry/c528e720-1d7e-481c-9f3f-2172226068db.pdf                             (page 0)    0.250000   0.000000   0.250000 (  0.251168)
samples/gedimat/augry/c528e720-1d7e-481c-9f3f-2172226068db.pdf                             (page 1)    0.220000   0.000000   0.220000 (  0.226148)
samples/gedimat/augry/c528e720-1d7e-481c-9f3f-2172226068db.pdf                             (page 2)    0.200000   0.000000   0.200000 (  0.201967)
samples/gedimat/delmonico_dorel/1cb28a95-0778-4fc6-baad-d34d3e7cd38f-1.pdf                 (page 0)    0.130000   0.000000   0.130000 (  0.132291)
samples/gedimat/delmonico_dorel/1cb28a95-0778-4fc6-baad-d34d3e7cd38f-1.pdf                 (page 1)    2.340000   0.000000   2.340000 (  2.339669)
samples/gedimat/delmonico_dorel/1cb28a95-0778-4fc6-baad-d34d3e7cd38f-1.pdf                 (page 2)    0.140000   0.000000   0.140000 (  0.136323)
samples/gedimat/delmonico_dorel/1cb28a95-0778-4fc6-baad-d34d3e7cd38f-1.pdf                 (page 3)    0.130000   0.000000   0.130000 (  0.130696)
...
```

I've taken the liberty of compiling all the PDFs with expensive page read (> 1sec) 
and sent them you to you by mail.
It might interest you.

**Comment by yob** [comment]
I had a look through the extra files you sent me.

In every case, the slow pages had more than 10,000 characters on them. The overlapping characters code is definitely to blame, but I can't see any more quick performance wins for now.

I'll try and release a new version with the performance fixes soon.
