### ISSUE TITLE
`PDF::Reader::Page#attributes` does not recursively dereference PDF Objects

### ISSUE THREAD

**Issue by jezhou** [yob/pdf-reader#319]
### Is this a bug or a feature request?

Either one or the other, not sure without more info

### What is the problem?

I came across a PDF recently that returns a bunch of `PDF::Reader::References` in place of values when I call `PDF::Reader::Page#attributes`, particularly for the `:MediaBox` and `:CropBox` keys. This was unexpected to me.

![image](https://user-images.githubusercontent.com/7007623/70669434-441acd00-1c2b-11ea-94d5-e9b6538675f8.png)

While I don't think this is typical of most PDFs, this is technically allowed in the specification (**7.3.10, Indirect Objects**).

> Any object in a pdf file may be labelled as an indirect object.

`PDF::Reader::Page#attributes`, however, doesn't use the `#deref!` method to recursively dereference the fields. This is a problem if I'm expecting `:MediaBox` or `:CropBox` to be an Array and not an Indirect Object.

https://github.com/yob/pdf-reader/blob/ed6aac13bb61aabd7cdafedbac39fcbaacc5e068/lib/pdf/reader/page.rb#L59-L69

### What do you expect?

I'm expecting any call to `PDF::Reader::Page#attributes` to return the dereferenced attributes.

The part I'm uncertain about is how much of this should be pushed onto the developers vs. how much should be done in the gem. I think it would be nice to include something like `PDF::Reader::Page#attributes!`, similar to how theres a `deref!` to `deref` that will dereference things recursively. But I would love any outside opinions on this.

If this isn't too much of a hard ask, I can file a pull-request if needed 🙂

**Comment by yob** [comment]
I don't have a clear answer for why the behaviour is the way it is.

One potential issues is that recursively dereferencing a `Page` object will including waling up the :Parent attribute, which then includes every other page in the PDF.

`PDF::Reader::Page` has some helper methods for extracting the page resources (like fonts), and they all do recursive dereferencing.

Maybe there's value in adding some additional helper methods that return other attributes (like the various page boxes) with auto dereferencing? That way we'd avoid walking up `Parent`.

It could either be a set of methods (`mediabox`, `cropbox`, etc), or maybe a single method that returns a Hash of all the boxes?

**Comment by jezhou** [comment]
> It could either be a set of methods (mediabox, cropbox, etc), or maybe a single method that returns a Hash of all the boxes?

@yob I kind of like this suggestion – there seem to be a default set of "boxes" a page can have according to the spec (7.7.3.3):

![image](https://user-images.githubusercontent.com/7007623/70855185-42474880-1e7b-11ea-84fe-9bd5d9aa43f9.png)

Would your suggestion be to recursively dereference these attributes only and return them as a hash in a new method (maybe called `boxes` or something)?

**Comment by yob** [comment]
> Would your suggestion be to recursively dereference these attributes only and return them as a hash in a new method (maybe called boxes or something)?

Yup, I'd accept a patch like that :)

I think it'd be good to keep the keys matching the PDF spec, so something like:

```ruby
def boxes
  {
    MediaBox: deref!(attributes[:MediaBox],
    ...
  }
)
  }
end
```
