### ISSUE TITLE
Reading text from PDF

### ISSUE THREAD

**Issue by ut** [yob/pdf-reader#324]
Hey,
I'm using pdf-reader to extract text from arbitrary pdf files, which works well in mose cases. 

But I have pdf documents, where the text extraction returns complete "letter salad". The PDF itself seems valid, I can open and print the file in Adobe Reader, I can copy text out of it, and text extraction with other programs like pdftotext went well.

pdf-reader output:

`$ reader.pages[1].text`

`F   P    d   e    P   G    w   V   s    H   D      m    t   B      f   a    d   b    u   m    w   V      E   F    .   D                  6      5      B       3\nu   l    i   t    l   r    r   l   h    h   i      n    n   r      d   f    r   r    d   n    a   n      t   r    J   i                  D      D      t       1\nr   e    B   r    i   p    n   s   a    e   B      .    d   i      s   B    h        z   s    z   F      c        l   B                  i      e              2\n    f    t   t    t   ,    .   a   r    H   t           e          i   s    ä   a    u   t    i   r      e   e    2   t                  R      G      f       8\nr   n    f   ,    n   a    i   r        a   f           n   m      h   t    g   r    r   t    w   i      i   r    1   f                  e      e      e       7\n,  `

I found nothing special in the documents metadata, it has some fonts with "coding: custom" though

Any thoughts?  Thanks in advance, Ulf

**Comment by yob** [comment]
I've dabbled in PDFs for years, but I'm still no expert.

It's hard to guess what might cause such wildly wrong symptoms. If you're able to email me a sample PDF I'm happy to take a look. Best case: I can identify the issue and generate a new PDF that replicates the problem (suitable for the test suite).

**Comment by yob** [comment]
Oh - my email here: https://yob.id.au/about.html

**Comment by ut** [comment]
Thanks! I'll send you an sampl. This will need  a tiny bit, since those PDF has been generated by someone else.

**Comment by yob** [comment]
The text extraction for the sample file you sent me is significantly better starting in 2.7.0, I suspect due to the fix in #403.

Sorry it took so long to get it sorted!
