### ISSUE TITLE
Can I extract data/text specifying coordinates? w, h, x, y?

### ISSUE THREAD

**Issue by djalmaaraujo** [yob/pdf-reader#327]
Hello @yob,

Imagine that I want to extract texts from a page passing the "areas".  Width Height X,  Y  Is there a method, easy solution for this? 

Thanks

**Comment by yob** [comment]
pdf-reader doesn't have support for this out of the box, although I can see it'd be a useful feature.

The quickest way to get this working for now is something based on the JSON extraction we discussed last year: https://gist.github.com/yob/d9e28e39943aec251cb570bf2879bda4. In theory, `JsonTextReceiver` could accept some co-ordinates for a box and throw away any characters outside that box.

**Comment by djalmaaraujo** [comment]
@yob Thanks, I forgot about this, thanks for reminding me. :)
