### ISSUE TITLE
Possibility of rubocop integration

### ISSUE THREAD

**Issue by ShockwaveNN** [yob/pdf-reader#334]
Hello, @yob 

I really like your gem and it's helping me at my job and I've got some spare time to integration [rubocop](https://github.com/rubocop-hq/rubocop) checks into your product.

Is this a good idea? Are you interested in it?

Simple test run of latest version of rubocop shown more than 5 thousand issue, of course not all of them fixable, and not all of them are real issue, more like code style variation, but some of them are definitely is something to fix

**Comment by yob** [comment]
Thanks for the suggestion @ShockwaveNN.

I quite like using a code style linter on team maintained projects. In this case I think I lean towards skipping rubocop - mainly because pdf-reader is reasonably stable, in maintenance mode with only occasional updates, and mostly maintained by just me.

**Comment by ShockwaveNN** [comment]
Ok, fair enough

In my experience if a project has good test coverage - it's pretty safe to integrate rubocop and it's fixes without any major side effects.

But since you're main maintainer - your word is the law.

Thank you for your good product
