### ISSUE TITLE
Allow Ascii85 version 1.1.0

### ISSUE THREAD

**Issue by jrochkind** [yob/pdf-reader#337]
The dependency on the Ascii85 gem says `"~> 1.0.0"`.  This actually means 1.0.x, it does not allow 1.1.0. 

https://github.com/yob/pdf-reader/blob/bf745436b2d3e7bebb51d0995d88574a96538206/pdf-reader.gemspec#L37

I suspect this may have been unintentional, usually we want to restrict to 1.x intead, any 1.anything but not 2.0. 

However an [Ascii85 1.1.0 was released November 12 2020](https://rubygems.org/gems/Ascii85/versions/1.1.0).  [Git compare changes](https://github.com/DataWraith/ascii85gem/compare/v1.0.1...v1.1.0)

Would it make sense to change pdf-reader dependenccy to `"Ascii85", "~> 1.0"`, and release, so projects with pdf-reader as a dependency can use the newest ascii85?

**Comment by yob** [comment]
Thanks for the prompt :heart:

**Comment by jrochkind** [comment]
Thank you!

**Comment by jrochkind** [comment]
Hope there will be a release including this change in the next few weeks/months or I may come back ha. 

(There's nothing particular in 1.1 I know I need, I just try to do `bundle outdated` now and then and figure out any unintentional blockers to keeping everything up to date, to not have to worry about any bugfixes or security patches I might not know about). 

Thanks for the gem, it's useful!
