### ISSUE TITLE
Error: undefined method '[]=' for nil:NilClass

### ISSUE THREAD

**Issue by pbalaban** [yob/pdf-reader#346]
First of all, thanks for creating this awesome gem!
I'm start searching inside PDF files and it helps me a lot.

Some of PDF files can not be processed correctly and the lib raises `undefined method '[]=' for nil:NilClass` error.
The issue is reproducible on version `2.4.2` with the [attached file](https://github.com/yob/pdf-reader/files/5900318/1397476_1_A.pdf) and the code below:

```
[3] pry(main)> PDF::Reader.new("1397476_1_A.pdf").pages.first.text
NoMethodError: undefined method `[]=' for nil:NilClass
from /home/peter/.rvm/gems/ruby-2.6.3@lytics/gems/pdf-reader-2.4.2/lib/pdf/reader/page_layout.rb:121:in `local_string_insert'
```

I tried to downgrade the version and it seems that issue appears somewhere between `2.0.0` and `2.1.0`

**Comment by yob** [comment]
Thanks for the clear report and sample file - I've added a fix and spec in #347.
