### ISSUE TITLE
slow parsing

### ISSUE THREAD

**Issue by martianinteractive** [yob/pdf-reader#36]
FYI, A 14 page pdf took 27 seconds to extract the text.

[12] pry(main)> Benchmark.realtime do
[12] pry(main)\*   pdf_file.pages.map{ |p| p.text }
[12] pry(main)\* end  
=> 27.4952540397644

Intel 2.2 GHz i7, 8GB RAM

**Comment by yob** [comment]
Thanks to the passage of time and hard work of the ruby core team, `pdf-reader` is now significantly faster on modern ruby versions. 

There'll always be improvements we can make, but I'm going to close this for now. If specific performance issues come up, I'm happy to investigate further.
