### ISSUE TITLE
Crash with no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by sebbASF** [yob/pdf-reader#366]
I have seen a crash at:
https://github.com/yob/pdf-reader/blob/6cc5c6663eb83c20ce5c43c06b3db716829ba969/lib/pdf/reader/buffer.rb#L238
no implicit conversion of nil into String (TypeError)

I think this is caused by 'chr = @io.read(1)' at line 235 which can return null at EOF.
Sorry, cannot share the PDF which caused this as it contains private info.

**Comment by yob** [comment]
Interesting. 

I can manually generate a file that raises that error with prawn like this:

```ruby
Prawn::Document.generate("hello.pdf") do
  text "This page has an invalid inline image"
  add_content("\n")
  add_content("BI")
  add_content("/W 16")
  add_content("/H 16")
  add_content("/BPC 1")
  add_content("/IM true")
  add_content("ID \xFEEI")
end
 ```

The relevant part of the content stream is:

```
BI
/W 16
/H 16
/BPC 1
/IM true
ID EI
Q
```
It never matches the first part of this conditional (the buffer doesn't start with white space or a NULL byte): https://github.com/yob/pdf-reader/blob/ecc6ffe22bef6f155526ca57de61d33ce9c2c0a0/lib/pdf/reader/buffer.rb#L233

In your file, what are the first 2-3 bytes after `ID`?

**Comment by sebbASF** [comment]
My tests did not find any issues, so I am have proposed the PR

**Comment by sebbASF** [comment]
Now fixed
