### ISSUE TITLE
Hello, world! appears as "! lro W , ll eH"

### ISSUE THREAD

**Issue by sebbASF** [yob/pdf-reader#376]
The page text parser shows "! lro W , ll eH" instead of "Hello World!" for the following PDF:

http://pdfsharp.com/PDFsharp/images/stories/samples/PDFs/HelloWorld.pdf

Seems that there is some incorrect text positioning happening.

**Comment by sebbASF** [comment]
The problem is that the X cursor position is being decremented rather than incremented when the letters are processed

Changing '-100 Tz' to ' 100 Tz' fixes the page text, but Preview reverses the output, so I suspect there is another value somewhere that is not being taken into account.

**Comment by yob** [comment]
The positioning issues in HelloWorld.pdf are addressed by the fixes I'm working on for #397. Hopefully I'll land them on main in the next few days and we can resolve this issue at the same time.
