### ISSUE TITLE
Reading text from PDF with fields

### ISSUE THREAD

**Issue by p0deje** [yob/pdf-reader#44]
Hi and first of all thanks for this awesome gem!

I have a PDF file taken from http://www.irs.gov/pub/irs-pdf/fw4.pdf and it contains fields to be filled. I fill some fields with, for example, `Blah-blah` and save a copy of PDF file. However, when I try to read its pages text, filled text is not shown.

``` ruby
reader = PDF::Reader.new('copy.pdf')
reader.page(1).text.include?('Blah-blah')
#=> false
```

**Comment by jobygoude** [comment]
Hi,

How can we extract AcroForm attributes list from reader ?
In the :Annots array, there are a list of PDF::Reader::Reference object but i don't find AcroForm attributes.

Thank You !

**Comment by ruinunes** [comment]
@jobygoude `objects.deref!(page.attributes[:Annots]).pluck(:T)`
I dislike to go page by page. @yob Is there a new way to get them all at once, like a that document level you speak of?
