### ISSUE TITLE
ValidatingReceiver is using 'call' instead of 'send' in method_missing

### ISSUE THREAD

**Issue by markpent** [yob/pdf-reader#441]
Sorry if I'm missing something, but after upgrading I am getting undefined method `call' for <my class> when calling walk.
Looking at ValidatingReceiver it seems to should be calling send to pass the non-validated callback to the wrapped class.

**Comment by yob** [comment]
Oops, a good old fashioned bug.

I've merged a fix, and will ship it as v2.9.1 shortly. Thanks for the report!
