### ISSUE TITLE
PDF::Reader::ObjectHash.get_page_objects: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by bcoles** [yob/pdf-reader#458]
This error is by far the most frequently encountered error during fuzzing.

```
crashes/20220417055748989526710_crash_497.pdf.trace-1-undefined method `[]' for nil:NilClass
crashes/20220417055748989526710_crash_497.pdf.trace:2:/var/lib/gems/2.7.0/gems/pdf-reader-2.9.2/lib/pdf/reader/object_hash.rb:576:in `get_page_objects'
```

[20220417055748989526710_crash_497.pdf](https://github.com/yob/pdf-reader/files/8501755/20220417055748989526710_crash_497.pdf)

I have not investigated the root cause. I have no idea how realistic this issue is outside of fuzzing. However, fixing this issue would significantly reduce the fuzzer output. This would speed up fuzzing and save disk space by not having to write the crash file and output to disk.

The surrounding code raises `MalformedPDFError` but these code paths are frequently missed.

https://github.com/yob/pdf-reader/blob/21d0d21051b6c5ae160cb281e19e4bb23c3f9e56/lib/pdf/reader/object_hash.rb#L570-L588

**Comment by yob** [comment]
woah, spooky. This was just converted to a `MalformedPDFError` by #457

**Comment by yob** [comment]
If you can confirm #457 fixes the crash for you in fuzzing, I'll close this issue.

**Comment by bcoles** [comment]
> If you can confirm #457 fixes the crash for you in fuzzing, I'll close this issue.

Re-running the fuzzer now. This issue appears to have been resolved.

```
user@ubuntu:~/Desktop/pdf-reader$ grep get_page_objects crashes/*.trace | wc -l
0
```

There would usually have been hundreds or thousands of these crashes by now.

```
user@ubuntu:~/Desktop/pdf-reader$ grep get_page_objects crashes.1/*.trace | wc -l
4140
user@ubuntu:~/Desktop/pdf-reader$ grep get_page_objects crashes.2/*.trace | wc -l
19736
```

![image](https://user-images.githubusercontent.com/434827/163717581-b1fc17fc-fc1b-4ca3-878c-0bddc3761448.png)
