### ISSUE TITLE
allow Ascii85 2.0?

### ISSUE THREAD

**Issue by jrochkind** [yob/pdf-reader#538]
The dependency gem `ascii85` has had a 2.0 release. 

https://github.com/DataWraith/ascii85gem/blob/master/CHANGELOG.md

It doesn't actually seem to have any breaking changes other than dropping support for old rubies?

Update pdf-reader to allow apps to install ascii85 2.0?

**Comment by yob** [comment]
Thanks, I hadn't noticed v2 was released!

I had a go, but ran into a failing spec that might indicate an unplanned behaviour change in v2. I've opened an issue to check: https://github.com/DataWraith/ascii85gem/issues/8

**Comment by juskoljo** [comment]
Encoding issue seems to be fixed in Ascii85 v2.01 that was released on Sep 15 👍

**Comment by yob** [comment]
Thanks for the reminder, this had fallen off my radar.

I've released v2.13.0 which relaxes the Ascii85 dependency :+1:
