### ISSUE TITLE
TypeError: nil can't be coerced into Fixnum

### ISSUE THREAD

**Issue by atonevski** [yob/pdf-reader#80]
When I try to access text from a page with 
 reader.page(95).text
I get an exception

TypeError: nil can't be coerced into Fixnum
    from /home/and/.gem/ruby/1.9.1/gems/pdf-reader-1.3.0/lib/pdf/reader/page_layout.rb:47:in `-'
    from /home/and/.gem/ruby/1.9.1/gems/pdf-reader-1.3.0/lib/pdf/reader/page_layout.rb:47:in`interesting_rows'
    from /home/and/.gem/ruby/1.9.1/gems/pdf-reader-1.3.0/lib/pdf/reader/page_layout.rb:33:in `to_s'
    from /home/and/.gem/ruby/1.9.1/gems/pdf-reader-1.3.0/lib/pdf/reader/page_text_receiver.rb:49:in`content'
    from /home/and/.gem/ruby/1.9.1/gems/pdf-reader-1.3.0/lib/pdf/reader/page.rb:72:in `text'
I can access any other page in the document without any problem.
Any thoughts about this?

**Comment by gordonbisnor** [comment]
I'm getting this error as well and wondering if the project is no longer maintained, or  has been moved to a new location etc?

**Comment by CaseKey** [comment]
I"m also getting this same error

**Comment by wjdhamilton** [comment]
:+1:
