### ISSUE TITLE
Saving a page as a separate PDF document

### ISSUE THREAD

**Issue by barmstrong** [yob/pdf-reader#81]
Thanks for the awesome gem!

Is there a way to save a page as it's own separate document?  Essentially breaking the PDF into separate documents (1 per page).

**Comment by kevshin2** [comment]
Any update on this? Thanks

**Comment by fernandokosh** [comment]
Any update on this?

**Comment by yob** [comment]
Currently I have no plans to add this to pdf-reader, sorry!
