### ISSUE TITLE
page.text only returns the copyright

### ISSUE THREAD

**Issue by bryanrasmussen** [yob/pdf-reader#82]
The pdf is generated from xsl-fo, so it is text, my code is the following:

def pdf_text(pdflocation)
  if $env == "local" then
    pdflocation = "sinatra_resources/example.pdf"
  end
  reader = PDF::Reader.new(pdflocation)
  text = ""
  reader.pages.each do |page|
      text += page.text
    end
return text
end

I call it with 
document = pdf_text(pdflocation)
which returns the last bit of text in the document, a copyright notice in the footer. 

My env is local, so I don't have any problems with finding the wrong pdf somehow. 
If I do pdftotext on the commandline I can get the whole document out
There is only one page in the test document, if I do reader.page(1).text I get the same thing, only the copyright in the page footer.

I'm supposing it's something I have totally misunderstood but what - I would assume page.text should get me all the text on the page?

**Comment by yob** [comment]
Thanks for taking the time to report this. I'm going to close it due to inactivity, but feel free to re-open if required.
